[profile.default]
src = "src"
test = "test"
libs = ["dependencies"]
evm_version = "paris"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"

[profile.default.fmt]
wrap_comments = true

[dependencies]
"forge-std" = { version = "1.9.6" }
"@openzeppelin-contracts" = { version = "5.0.2" }
